//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "import_batches")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub owner_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub file_name: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub file_hash: Vec<u8>,
    pub year: i32,
    pub month: i32,
    pub row_count: i32,
    pub imported_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::transactions_raw::Entity")]
    TransactionsRaw,
}

impl Related<super::transactions_raw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionsRaw.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
