//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "transactions_raw")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub owner_id: Uuid,
    pub import_batch_id: Uuid,
    pub row_index: i32,
    pub group_id: Uuid,
    pub is_group_header: bool,
    pub occurred_on: Option<Date>,
    #[sea_orm(column_type = "Double", nullable)]
    pub raw_date_serial: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub merchant_text: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub actor_text: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub category_text: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub total_amount: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub memo: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((15, 4)))", nullable)]
    pub unit_price: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 4)))", nullable)]
    pub quantity: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))", nullable)]
    pub line_amount: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub payment_text: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub evidence_text: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub extras: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::import_batches::Entity",
        from = "Column::ImportBatchId",
        to = "super::import_batches::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ImportBatches,
    #[sea_orm(has_many = "super::transactions::Entity")]
    Transactions,
}

impl Related<super::import_batches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImportBatches.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
