//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub owner_id: Uuid,
    pub raw_id: Uuid,
    pub group_id: Uuid,
    pub occurred_on: Date,
    pub merchant_id: Option<Uuid>,
    pub actor_id: Option<Uuid>,
    pub category_id: Option<Uuid>,
    pub product_id: Option<Uuid>,
    pub payment_method_id: Option<Uuid>,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((15, 4)))", nullable)]
    pub unit_price: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((15, 4)))", nullable)]
    pub quantity: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub memo: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::categories::Entity",
        from = "Column::CategoryId",
        to = "super::categories::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Categories,
    #[sea_orm(
        belongs_to = "super::ledger_actors::Entity",
        from = "Column::ActorId",
        to = "super::ledger_actors::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    LedgerActors,
    #[sea_orm(
        belongs_to = "super::merchants::Entity",
        from = "Column::MerchantId",
        to = "super::merchants::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Merchants,
    #[sea_orm(
        belongs_to = "super::payment_methods::Entity",
        from = "Column::PaymentMethodId",
        to = "super::payment_methods::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PaymentMethods,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Products,
    #[sea_orm(
        belongs_to = "super::transactions_raw::Entity",
        from = "Column::RawId",
        to = "super::transactions_raw::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TransactionsRaw,
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Categories.def()
    }
}

impl Related<super::ledger_actors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LedgerActors.def()
    }
}

impl Related<super::merchants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Merchants.def()
    }
}

impl Related<super::payment_methods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentMethods.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::transactions_raw::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionsRaw.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
